elasticsearch:
  image: elasticsearch:latest
  container_name: elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
  - "9200:9200"
  volumes:
  - /etc/localtime:/etc/localtime
  - ./elasticsearch/data:/usr/share/elasticsearch/data
  - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "2"
    
kibana:
  image: kibana:latest
  container_name: kibana
  ports:
  - "5601:5601"
  links:
  - elasticsearch
  volumes:
  - /etc/localtime:/etc/localtime
  - ./kibana/installedPlugins:/opt/kibana/installedPlugins
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "2"

# ElasticSearch install head plugin
# $   docker exec -ti elasticsearch bash
# $   ./bin/plugin install mobz/elasticsearch-head
# $   exit

# Kibana install sense plugin
# $   docker exec -ti kibana bash
# $   cd /opt/kibana/ 
# $   ./bin/kibana plugin --install elastic/sense
# $   exit
